function Hd = getFilter
%GETFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 19-Apr-2019 21:51:39

Fpass = 200;    % Passband Frequency
Fstop = 400;    % Stopband Frequency
Apass = 0.2;    % Passband Ripple (dB)
Astop = 60;     % Stopband Attenuation (dB)
Fs    = 10000;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

Hd = design(h, 'ifir');


